# Render Blueprint for NotionShare
# Deploy: https://dashboard.render.com/select-repo

services:
  # Backend API
  - type: web
    name: notionshare-api
    env: python
    region: oregon
    plan: starter
    branch: main
    buildCommand: pip install -r backend/requirements.txt
    startCommand: cd backend && uvicorn app.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: notionshare-db
          property: connectionString
      - key: REDIS_URL
        fromService:
          type: redis
          name: notionshare-redis
          property: connectionString
      - key: JWT_SECRET_KEY
        generateValue: true
      - key: JWT_ALGORITHM
        value: HS256
      - key: JWT_EXPIRE_MINUTES
        value: 1440
      - key: ENVIRONMENT
        value: production
      - key: FRONTEND_URL
        value: https://yourusername.github.io/notionshare
      - key: CORS_ORIGINS
        value: https://yourusername.github.io
      - key: CELERY_BROKER_URL
        fromService:
          type: redis
          name: notionshare-redis
          property: connectionString
      - key: CELERY_RESULT_BACKEND
        fromService:
          type: redis
          name: notionshare-redis
          property: connectionString
      - key: NOTION_CLIENT_ID
        sync: false
      - key: NOTION_CLIENT_SECRET
        sync: false
      - key: NOTION_REDIRECT_URI
        value: https://notionshare-api.onrender.com/api/v1/auth/notion/callback

  # Celery Worker
  - type: worker
    name: notionshare-worker
    env: python
    region: oregon
    plan: starter
    branch: main
    buildCommand: pip install -r backend/requirements.txt
    startCommand: cd backend && celery -A app.tasks.celery_app worker --loglevel=info
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: notionshare-db
          property: connectionString
      - key: REDIS_URL
        fromService:
          type: redis
          name: notionshare-redis
          property: connectionString
      - key: CELERY_BROKER_URL
        fromService:
          type: redis
          name: notionshare-redis
          property: connectionString
      - key: CELERY_RESULT_BACKEND
        fromService:
          type: redis
          name: notionshare-redis
          property: connectionString

  # Celery Beat (Scheduler)
  - type: worker
    name: notionshare-beat
    env: python
    region: oregon
    plan: starter
    branch: main
    buildCommand: pip install -r backend/requirements.txt
    startCommand: cd backend && celery -A app.tasks.celery_app beat --loglevel=info
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: notionshare-db
          property: connectionString
      - key: REDIS_URL
        fromService:
          type: redis
          name: notionshare-redis
          property: connectionString
      - key: CELERY_BROKER_URL
        fromService:
          type: redis
          name: notionshare-redis
          property: connectionString
      - key: CELERY_RESULT_BACKEND
        fromService:
          type: redis
          name: notionshare-redis
          property: connectionString

databases:
  - name: notionshare-db
    databaseName: notionshare
    plan: starter
    region: oregon

  - name: notionshare-redis
    plan: starter
    region: oregon
