"""Add row-level permissions support

Revision ID: e5dd58bb77df
Revises: 
Create Date: 2025-10-25 10:57:50.953285

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e5dd58bb77df'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_permission_row_filters',
    sa.Column('user_permission_id', sa.Integer(), nullable=False),
    sa.Column('row_filter_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['row_filter_id'], ['row_filters.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_permission_id'], ['user_permissions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_permission_id', 'row_filter_id')
    )
    op.add_column('database_configs', sa.Column('parent_page_id', sa.String(length=255), nullable=True))

    # Migrate data: copy target_page_id to parent_page_id
    op.execute('UPDATE database_configs SET parent_page_id = target_page_id WHERE target_page_id IS NOT NULL')

    op.drop_column('database_configs', 'target_database_id')
    op.drop_column('database_configs', 'target_page_id')
    op.add_column('user_permissions', sa.Column('user_page_id', sa.String(length=255), nullable=True))
    op.add_column('user_permissions', sa.Column('target_database_id', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_permissions', 'target_database_id')
    op.drop_column('user_permissions', 'user_page_id')
    op.add_column('database_configs', sa.Column('target_page_id', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('database_configs', sa.Column('target_database_id', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_column('database_configs', 'parent_page_id')
    op.drop_table('user_permission_row_filters')
    # ### end Alembic commands ###
